### ISSUE TITLE
PEMS03 MAPE

### ISSUE THREAD

**Issue by liuaoy** [jeongwhanchoi/STG-NCDE#3]
![image](https://user-images.githubusercontent.com/45134622/165667245-81c21405-a3f0-43f7-a55b-d6c21983c561.png)
Hello, why does MAPE have this problem on PEMS03?

**Comment by wengwenchao123** [comment]
> ![image](https://user-images.githubusercontent.com/45134622/165667245-81c21405-a3f0-43f7-a55b-d6c21983c561.png) Hello, why does MAPE have this problem on PEMS03?

Friend, have you solved this problem? I have also encountered this problem. I don't know what to do

**Comment by liuaoy** [comment]
> 

Unfortunately, I did not solve this problem.

**Comment by liuxu77** [comment]
To solve this, you can set the MAPE threshold to the smallest value in the label (i.e., torch.min(label).cpu()) rather than using the default threshold zero.
