### ISSUE TITLE
Longer time-series input may performs bad?

### ISSUE THREAD

**Issue by lixus7** [jeongwhanchoi/STG-NCDE#4]
Congratudate for your AAAI 2022 work. It's a nice work, but i met some problem when i use your model as a sota in my experiment. It performed very bad when i try to input 16, 24 or 144 steps in electricity and bikeNYC dataset. Even though i try to adjust some parameters like node_embedd dim, Chenb_k (1,2,3), hidden channel (16 may be the best), loss function (L2 and L1), it stilll does not make. I would like to inform you for some good solutions to solve it. I will appreciate it very much if there are some replies.

**Comment by Ricky1601904881** [comment]
> Congratudate for your AAAI 2022 work. It's a nice work, but i met some problem when i use your model as a sota in my experiment. It performed very bad when i try to input 16, 24 or 144 steps in electricity and bikeNYC dataset. Even though i try to adjust some parameters like node_embedd dim, Chenb_k (1,2,3), hidden channel (16 may be the best), loss function (L2 and L1), it stilll does not make. I would like to inform you for some good solutions to solve it. I will appreciate it very much if there are some replies.

I've encountered the same problem when trying to apply NCDE on longer time series (in fact 1500 steps). Could you please share your solutions with me? Is it about NRDE? Thanks.

**Comment by jeongwhanchoi** [comment]
Hello @lixus7. We are still exploring longer time-series. It would be beneficial if you could share good information about the dataset you experimented with.

Note: we have a paper related to NRDE under journal review.
